/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndiceEntregaRouteImport } from './routes/indice-entrega'
import { Route as GestaoAcompanhamentoRouteImport } from './routes/gestao.acompanhamento'
import { Route as GestaoNovaRouteImport } from './routes/gestao.nova'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndiceEntregaRoute = IndiceEntregaRouteImport.update({
  id: '/indice-entrega',
  path: '/indice-entrega',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoAcompanhamentoRoute = GestaoAcompanhamentoRouteImport.update({
  id: '/gestao/acompanhamento',
  path: '/gestao/acompanhamento',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoNovaRoute = GestaoNovaRouteImport.update({
  id: '/gestao/nova',
  path: '/gestao/nova',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/indice-entrega': typeof IndiceEntregaRoute
  '/gestao/acompanhamento': typeof GestaoAcompanhamentoRoute
  '/gestao/nova': typeof GestaoNovaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/indice-entrega': typeof IndiceEntregaRoute
  '/gestao/acompanhamento': typeof GestaoAcompanhamentoRoute
  '/gestao/nova': typeof GestaoNovaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/indice-entrega': typeof IndiceEntregaRoute
  '/gestao/acompanhamento': typeof GestaoAcompanhamentoRoute
  '/gestao/nova': typeof GestaoNovaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/$' | '/indice-entrega' | '/gestao/acompanhamento' | '/gestao/nova'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/indice-entrega' | '/gestao/acompanhamento' | '/gestao/nova'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/indice-entrega'
    | '/gestao/acompanhamento'
    | '/gestao/nova'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  IndiceEntregaRoute: typeof IndiceEntregaRoute
  GestaoAcompanhamentoRoute: typeof GestaoAcompanhamentoRoute
  GestaoNovaRoute: typeof GestaoNovaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indice-entrega': {
      id: '/indice-entrega'
      path: '/indice-entrega'
      fullPath: '/indice-entrega'
      preLoaderRoute: typeof IndiceEntregaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao/acompanhamento': {
      id: '/gestao/acompanhamento'
      path: '/gestao/acompanhamento'
      fullPath: '/gestao/acompanhamento'
      preLoaderRoute: typeof GestaoAcompanhamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao/nova': {
      id: '/gestao/nova'
      path: '/gestao/nova'
      fullPath: '/gestao/nova'
      preLoaderRoute: typeof GestaoNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  IndiceEntregaRoute: IndiceEntregaRoute,
  GestaoAcompanhamentoRoute: GestaoAcompanhamentoRoute,
  GestaoNovaRoute: GestaoNovaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
