/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCarteiraRouteImport } from './routes/_authenticated/carteira'
import { Route as AuthenticatedCarteiraInteligenteRouteImport } from './routes/_authenticated/carteira-inteligente'
import { Route as AuthenticatedCurriculosBpoRouteImport } from './routes/_authenticated/curriculos-bpo'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedMinhasSolicitacoesRouteImport } from './routes/_authenticated/minhas-solicitacoes'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedGestaoIndexRouteImport } from './routes/_authenticated/gestao.index'
import { Route as AuthenticatedGestaoDepartamentoPessoalRouteImport } from './routes/_authenticated/gestao.departamento-pessoal'
import { Route as AuthenticatedGestaoFinanceiroRouteImport } from './routes/_authenticated/gestao.financeiro'
import { Route as AuthenticatedGestaoFiscalRouteImport } from './routes/_authenticated/gestao.fiscal'
import { Route as AuthenticatedGestaoModulosRouteImport } from './routes/_authenticated/gestao.modulos'
import { Route as AuthenticatedGestaoFiscalIndexRouteImport } from './routes/_authenticated/gestao.fiscal.index'
import { Route as AuthenticatedGestaoFiscalCarteiraRouteImport } from './routes/_authenticated/gestao.fiscal.carteira'
import { Route as AuthenticatedGestaoFiscalCurriculosRouteImport } from './routes/_authenticated/gestao.fiscal.curriculos'
import { Route as AuthenticatedGestaoFiscalEquipeRouteImport } from './routes/_authenticated/gestao.fiscal.equipe'
import { Route as AuthenticatedGestaoSolicitacoesExternalIdRouteImport } from './routes/_authenticated/gestao.solicitacoes.$externalId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarteiraRoute = AuthenticatedCarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarteiraInteligenteRoute =
  AuthenticatedCarteiraInteligenteRouteImport.update({
    id: '/carteira-inteligente',
    path: '/carteira-inteligente',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCurriculosBpoRoute =
  AuthenticatedCurriculosBpoRouteImport.update({
    id: '/curriculos-bpo',
    path: '/curriculos-bpo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhasSolicitacoesRoute =
  AuthenticatedMinhasSolicitacoesRouteImport.update({
    id: '/minhas-solicitacoes',
    path: '/minhas-solicitacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedGestaoIndexRoute =
  AuthenticatedGestaoIndexRouteImport.update({
    id: '/gestao/',
    path: '/gestao/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGestaoDepartamentoPessoalRoute =
  AuthenticatedGestaoDepartamentoPessoalRouteImport.update({
    id: '/gestao/departamento-pessoal',
    path: '/gestao/departamento-pessoal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGestaoFinanceiroRoute =
  AuthenticatedGestaoFinanceiroRouteImport.update({
    id: '/gestao/financeiro',
    path: '/gestao/financeiro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGestaoFiscalRoute =
  AuthenticatedGestaoFiscalRouteImport.update({
    id: '/gestao/fiscal',
    path: '/gestao/fiscal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGestaoModulosRoute =
  AuthenticatedGestaoModulosRouteImport.update({
    id: '/gestao/modulos',
    path: '/gestao/modulos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGestaoFiscalIndexRoute =
  AuthenticatedGestaoFiscalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGestaoFiscalRoute,
  } as any)
const AuthenticatedGestaoFiscalCarteiraRoute =
  AuthenticatedGestaoFiscalCarteiraRouteImport.update({
    id: '/carteira',
    path: '/carteira',
    getParentRoute: () => AuthenticatedGestaoFiscalRoute,
  } as any)
const AuthenticatedGestaoFiscalCurriculosRoute =
  AuthenticatedGestaoFiscalCurriculosRouteImport.update({
    id: '/curriculos',
    path: '/curriculos',
    getParentRoute: () => AuthenticatedGestaoFiscalRoute,
  } as any)
const AuthenticatedGestaoFiscalEquipeRoute =
  AuthenticatedGestaoFiscalEquipeRouteImport.update({
    id: '/equipe',
    path: '/equipe',
    getParentRoute: () => AuthenticatedGestaoFiscalRoute,
  } as any)
const AuthenticatedGestaoSolicitacoesExternalIdRoute =
  AuthenticatedGestaoSolicitacoesExternalIdRouteImport.update({
    id: '/gestao/solicitacoes/$externalId',
    path: '/gestao/solicitacoes/$externalId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/carteira': typeof AuthenticatedCarteiraRoute
  '/carteira-inteligente': typeof AuthenticatedCarteiraInteligenteRoute
  '/curriculos-bpo': typeof AuthenticatedCurriculosBpoRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/minhas-solicitacoes': typeof AuthenticatedMinhasSolicitacoesRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/gestao/departamento-pessoal': typeof AuthenticatedGestaoDepartamentoPessoalRoute
  '/gestao/financeiro': typeof AuthenticatedGestaoFinanceiroRoute
  '/gestao/fiscal': typeof AuthenticatedGestaoFiscalRouteWithChildren
  '/gestao/modulos': typeof AuthenticatedGestaoModulosRoute
  '/gestao/': typeof AuthenticatedGestaoIndexRoute
  '/gestao/fiscal/carteira': typeof AuthenticatedGestaoFiscalCarteiraRoute
  '/gestao/fiscal/curriculos': typeof AuthenticatedGestaoFiscalCurriculosRoute
  '/gestao/fiscal/equipe': typeof AuthenticatedGestaoFiscalEquipeRoute
  '/gestao/solicitacoes/$externalId': typeof AuthenticatedGestaoSolicitacoesExternalIdRoute
  '/gestao/fiscal/': typeof AuthenticatedGestaoFiscalIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/carteira': typeof AuthenticatedCarteiraRoute
  '/carteira-inteligente': typeof AuthenticatedCarteiraInteligenteRoute
  '/curriculos-bpo': typeof AuthenticatedCurriculosBpoRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/minhas-solicitacoes': typeof AuthenticatedMinhasSolicitacoesRoute
  '/': typeof AuthenticatedIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/gestao/departamento-pessoal': typeof AuthenticatedGestaoDepartamentoPessoalRoute
  '/gestao/financeiro': typeof AuthenticatedGestaoFinanceiroRoute
  '/gestao/modulos': typeof AuthenticatedGestaoModulosRoute
  '/gestao': typeof AuthenticatedGestaoIndexRoute
  '/gestao/fiscal/carteira': typeof AuthenticatedGestaoFiscalCarteiraRoute
  '/gestao/fiscal/curriculos': typeof AuthenticatedGestaoFiscalCurriculosRoute
  '/gestao/fiscal/equipe': typeof AuthenticatedGestaoFiscalEquipeRoute
  '/gestao/solicitacoes/$externalId': typeof AuthenticatedGestaoSolicitacoesExternalIdRoute
  '/gestao/fiscal': typeof AuthenticatedGestaoFiscalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/carteira': typeof AuthenticatedCarteiraRoute
  '/_authenticated/carteira-inteligente': typeof AuthenticatedCarteiraInteligenteRoute
  '/_authenticated/curriculos-bpo': typeof AuthenticatedCurriculosBpoRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/minhas-solicitacoes': typeof AuthenticatedMinhasSolicitacoesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/gestao/departamento-pessoal': typeof AuthenticatedGestaoDepartamentoPessoalRoute
  '/_authenticated/gestao/financeiro': typeof AuthenticatedGestaoFinanceiroRoute
  '/_authenticated/gestao/fiscal': typeof AuthenticatedGestaoFiscalRouteWithChildren
  '/_authenticated/gestao/modulos': typeof AuthenticatedGestaoModulosRoute
  '/_authenticated/gestao/': typeof AuthenticatedGestaoIndexRoute
  '/_authenticated/gestao/fiscal/carteira': typeof AuthenticatedGestaoFiscalCarteiraRoute
  '/_authenticated/gestao/fiscal/curriculos': typeof AuthenticatedGestaoFiscalCurriculosRoute
  '/_authenticated/gestao/fiscal/equipe': typeof AuthenticatedGestaoFiscalEquipeRoute
  '/_authenticated/gestao/solicitacoes/$externalId': typeof AuthenticatedGestaoSolicitacoesExternalIdRoute
  '/_authenticated/gestao/fiscal/': typeof AuthenticatedGestaoFiscalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/carteira'
    | '/carteira-inteligente'
    | '/curriculos-bpo'
    | '/equipe'
    | '/minhas-solicitacoes'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/gestao/departamento-pessoal'
    | '/gestao/financeiro'
    | '/gestao/fiscal'
    | '/gestao/modulos'
    | '/gestao/'
    | '/gestao/fiscal/carteira'
    | '/gestao/fiscal/curriculos'
    | '/gestao/fiscal/equipe'
    | '/gestao/solicitacoes/$externalId'
    | '/gestao/fiscal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/carteira'
    | '/carteira-inteligente'
    | '/curriculos-bpo'
    | '/equipe'
    | '/minhas-solicitacoes'
    | '/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/gestao/departamento-pessoal'
    | '/gestao/financeiro'
    | '/gestao/modulos'
    | '/gestao'
    | '/gestao/fiscal/carteira'
    | '/gestao/fiscal/curriculos'
    | '/gestao/fiscal/equipe'
    | '/gestao/solicitacoes/$externalId'
    | '/gestao/fiscal'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/carteira'
    | '/_authenticated/carteira-inteligente'
    | '/_authenticated/curriculos-bpo'
    | '/_authenticated/equipe'
    | '/_authenticated/minhas-solicitacoes'
    | '/_authenticated/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/gestao/departamento-pessoal'
    | '/_authenticated/gestao/financeiro'
    | '/_authenticated/gestao/fiscal'
    | '/_authenticated/gestao/modulos'
    | '/_authenticated/gestao/'
    | '/_authenticated/gestao/fiscal/carteira'
    | '/_authenticated/gestao/fiscal/curriculos'
    | '/_authenticated/gestao/fiscal/equipe'
    | '/_authenticated/gestao/solicitacoes/$externalId'
    | '/_authenticated/gestao/fiscal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carteira': {
      id: '/_authenticated/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof AuthenticatedCarteiraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carteira-inteligente': {
      id: '/_authenticated/carteira-inteligente'
      path: '/carteira-inteligente'
      fullPath: '/carteira-inteligente'
      preLoaderRoute: typeof AuthenticatedCarteiraInteligenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curriculos-bpo': {
      id: '/_authenticated/curriculos-bpo'
      path: '/curriculos-bpo'
      fullPath: '/curriculos-bpo'
      preLoaderRoute: typeof AuthenticatedCurriculosBpoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minhas-solicitacoes': {
      id: '/_authenticated/minhas-solicitacoes'
      path: '/minhas-solicitacoes'
      fullPath: '/minhas-solicitacoes'
      preLoaderRoute: typeof AuthenticatedMinhasSolicitacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/gestao/': {
      id: '/_authenticated/gestao/'
      path: '/gestao'
      fullPath: '/gestao/'
      preLoaderRoute: typeof AuthenticatedGestaoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestao/departamento-pessoal': {
      id: '/_authenticated/gestao/departamento-pessoal'
      path: '/gestao/departamento-pessoal'
      fullPath: '/gestao/departamento-pessoal'
      preLoaderRoute: typeof AuthenticatedGestaoDepartamentoPessoalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestao/financeiro': {
      id: '/_authenticated/gestao/financeiro'
      path: '/gestao/financeiro'
      fullPath: '/gestao/financeiro'
      preLoaderRoute: typeof AuthenticatedGestaoFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestao/fiscal': {
      id: '/_authenticated/gestao/fiscal'
      path: '/gestao/fiscal'
      fullPath: '/gestao/fiscal'
      preLoaderRoute: typeof AuthenticatedGestaoFiscalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestao/modulos': {
      id: '/_authenticated/gestao/modulos'
      path: '/gestao/modulos'
      fullPath: '/gestao/modulos'
      preLoaderRoute: typeof AuthenticatedGestaoModulosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestao/fiscal/': {
      id: '/_authenticated/gestao/fiscal/'
      path: '/'
      fullPath: '/gestao/fiscal/'
      preLoaderRoute: typeof AuthenticatedGestaoFiscalIndexRouteImport
      parentRoute: typeof AuthenticatedGestaoFiscalRoute
    }
    '/_authenticated/gestao/fiscal/carteira': {
      id: '/_authenticated/gestao/fiscal/carteira'
      path: '/carteira'
      fullPath: '/gestao/fiscal/carteira'
      preLoaderRoute: typeof AuthenticatedGestaoFiscalCarteiraRouteImport
      parentRoute: typeof AuthenticatedGestaoFiscalRoute
    }
    '/_authenticated/gestao/fiscal/curriculos': {
      id: '/_authenticated/gestao/fiscal/curriculos'
      path: '/curriculos'
      fullPath: '/gestao/fiscal/curriculos'
      preLoaderRoute: typeof AuthenticatedGestaoFiscalCurriculosRouteImport
      parentRoute: typeof AuthenticatedGestaoFiscalRoute
    }
    '/_authenticated/gestao/fiscal/equipe': {
      id: '/_authenticated/gestao/fiscal/equipe'
      path: '/equipe'
      fullPath: '/gestao/fiscal/equipe'
      preLoaderRoute: typeof AuthenticatedGestaoFiscalEquipeRouteImport
      parentRoute: typeof AuthenticatedGestaoFiscalRoute
    }
    '/_authenticated/gestao/solicitacoes/$externalId': {
      id: '/_authenticated/gestao/solicitacoes/$externalId'
      path: '/gestao/solicitacoes/$externalId'
      fullPath: '/gestao/solicitacoes/$externalId'
      preLoaderRoute: typeof AuthenticatedGestaoSolicitacoesExternalIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedGestaoFiscalRouteChildren {
  AuthenticatedGestaoFiscalCarteiraRoute: typeof AuthenticatedGestaoFiscalCarteiraRoute
  AuthenticatedGestaoFiscalCurriculosRoute: typeof AuthenticatedGestaoFiscalCurriculosRoute
  AuthenticatedGestaoFiscalEquipeRoute: typeof AuthenticatedGestaoFiscalEquipeRoute
  AuthenticatedGestaoFiscalIndexRoute: typeof AuthenticatedGestaoFiscalIndexRoute
}

const AuthenticatedGestaoFiscalRouteChildren: AuthenticatedGestaoFiscalRouteChildren =
  {
    AuthenticatedGestaoFiscalCarteiraRoute:
      AuthenticatedGestaoFiscalCarteiraRoute,
    AuthenticatedGestaoFiscalCurriculosRoute:
      AuthenticatedGestaoFiscalCurriculosRoute,
    AuthenticatedGestaoFiscalEquipeRoute: AuthenticatedGestaoFiscalEquipeRoute,
    AuthenticatedGestaoFiscalIndexRoute: AuthenticatedGestaoFiscalIndexRoute,
  }

const AuthenticatedGestaoFiscalRouteWithChildren =
  AuthenticatedGestaoFiscalRoute._addFileChildren(
    AuthenticatedGestaoFiscalRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCarteiraRoute: typeof AuthenticatedCarteiraRoute
  AuthenticatedCarteiraInteligenteRoute: typeof AuthenticatedCarteiraInteligenteRoute
  AuthenticatedCurriculosBpoRoute: typeof AuthenticatedCurriculosBpoRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedMinhasSolicitacoesRoute: typeof AuthenticatedMinhasSolicitacoesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedGestaoDepartamentoPessoalRoute: typeof AuthenticatedGestaoDepartamentoPessoalRoute
  AuthenticatedGestaoFinanceiroRoute: typeof AuthenticatedGestaoFinanceiroRoute
  AuthenticatedGestaoFiscalRoute: typeof AuthenticatedGestaoFiscalRouteWithChildren
  AuthenticatedGestaoModulosRoute: typeof AuthenticatedGestaoModulosRoute
  AuthenticatedGestaoIndexRoute: typeof AuthenticatedGestaoIndexRoute
  AuthenticatedGestaoSolicitacoesExternalIdRoute: typeof AuthenticatedGestaoSolicitacoesExternalIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCarteiraRoute: AuthenticatedCarteiraRoute,
  AuthenticatedCarteiraInteligenteRoute: AuthenticatedCarteiraInteligenteRoute,
  AuthenticatedCurriculosBpoRoute: AuthenticatedCurriculosBpoRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedMinhasSolicitacoesRoute: AuthenticatedMinhasSolicitacoesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedGestaoDepartamentoPessoalRoute:
    AuthenticatedGestaoDepartamentoPessoalRoute,
  AuthenticatedGestaoFinanceiroRoute: AuthenticatedGestaoFinanceiroRoute,
  AuthenticatedGestaoFiscalRoute: AuthenticatedGestaoFiscalRouteWithChildren,
  AuthenticatedGestaoModulosRoute: AuthenticatedGestaoModulosRoute,
  AuthenticatedGestaoIndexRoute: AuthenticatedGestaoIndexRoute,
  AuthenticatedGestaoSolicitacoesExternalIdRoute:
    AuthenticatedGestaoSolicitacoesExternalIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
